import {Outfit , Ovo} from "next/font/google";
import "./globals.css";

const font1= Outfit({
  subsets: ["latin"], weight: ['400','500','600','700']
});


const font2 = Ovo({
  // variable: "--font-geist-mono",
   subsets: ["latin"], weight: ['400']
});

export const metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${font1.className} ${font2.className} antialiased leading-8 overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
